name: komikap
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  flutter_riverpod: ^2.4.0
  cached_network_image: ^3.3.0
  shared_preferences: ^2.2.2
  firebase_core: ^3.15.2
  cloud_firestore: ^5.0.0
  firebase_auth: ^5.7.0
  firebase_storage: ^12.0.0
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  path: ^1.8.3
  uuid: ^4.0.0
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
